### ISSUE TITLE
 Training NV3D dataset

### ISSUE THREAD

**Issue by JunhyeongDoyle** [aoliao12138/ReRF#2]
Hello,

First of all, thank you for sharing your excellent work. I am planning to train the ReRF model on the NV3D dataset and was wondering what the best configuration for the data type would be. I am considering setting it as 'llff'.

If there are any specific considerations or precautions I need to be aware of when changing the data loader and altering the data format, I would greatly appreciate your guidance.

Thanks : )

**Comment by aoliao12138** [comment]
Hello,

I'm glad you're interested in using the ReRF model and working with the NV3D dataset. Thank you for your kind words! I think it is a good choice to modify or inherit the dataloader of 'llff'.

**Comment by LabubuJ** [comment]
Hello! Does your revised program succeeded on the NV3D dataset flame_salmon?

**Comment by JunhyeongDoyle** [comment]
@JiaoChenGuang-JiaoHan  In my repository, there is adjusted model from ReRF for llff dataset. NV3D dataset is available on my version but it is needed to improve more for enhance qualities. 

I recommend you to try mine, and please notice me if you have any problem. thanks :)

**Comment by LabubuJ** [comment]
@JunhyeongDoyle  Thanks! I'm actually using your code, it helps me a lot. However, i have no idea of creating the config file of scenes in NV3D dataset(especially, flame_salmon). Can you give me any advice? Besides, I tried to modify your fan.py config file, but the result doesn't looks well.

**Comment by JunhyeongDoyle** [comment]
@JiaoChenGuang-JiaoHan  I'm glad to hear that my code was helpful. I totally agree with your opinion that modifying or creating config file is such complicate. In my case, I examined DVGO model which is backbone of ReRF cause DVGO is adaptable for custom llff data such as flame_salmon. I recommend you to search detail implementation on DVGO with llff dataset, there is also example config file for your case.

**Comment by LabubuJ** [comment]
Thanks for your reply , I will continue to find a proper config file.

**Comment by wunan96nj** [comment]
@JiaoChenGuang-JiaoHan Hi! have you found a proper config file for training the NV3D dataset?
